version: "3"
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${RENDER_EXTERNAL_HOSTNAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${RENDER_EXTERNAL_HOSTNAME}
    volumes:
      - n8n-data:/home/node/.n8n
volumes:
  n8n-data:
